### ISSUE TITLE
Simplify Pause Functions?

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/curation-protocol#11]
@iainnash I think we could simplify the UX of the pause functionality by changing it to a toggle that flips whatever the pause state is. This prevents ppl from trying to pass in a pause state that is already active, and also removes another param that has to get passed in on the front end. What do you think?

Pause functionality is present in line 166-182 in [curator.sol](https://github.com/public-assembly/curation-protocol/blob/main/src/Curator.sol)

**Comment by iainnash** [comment]
I like the ability for a user to pass in a pause boolean. I'd argue against toggling since sometimes requests can come out of order or via a multisig and should validate the expected behavior.

**Comment by 0xTranqui** [comment]
gotchu. I dont have a prob with keeping it as it, but maybe we could pair it with some custom events / extra checks in the write calls to prevent ppl from calling resume/pause when it is already set to that?
