### ISSUE TITLE
Add in chain Id param to Listings struct to prep for multi chain future?

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/curation-protocol#19]
Neokry from Artiva suggested adding this in if possible so that this whole implementaiton can be prepped for future of multi chain listings. I am VERY in support of this, not sure if there is any room left in the struct tho...

cc @iainnash

**Comment by iainnash** [comment]
Agreed. We can shorten short order for this.

**Comment by 0xTranqui** [comment]
this makes me happy
